# small try

#assert 1 == 2, "It's an error"

assert 1 == 1, "It's not an error"

number = 100
assert number > 0, f"number greater than 0 expected : {number}"

number = -100
assert number > 0, f"number greater than 0 expected : {number}"

# AssertionError: hello WTF

print('Program ended...')
